# Generated by Django 4.0.4 on 2022-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=30)),
                ('Blog', models.IntegerField()),
                ('post_date', models.DateField()),
            ],
        ),
    ]
