# Generated by Django 4.0.4 on 2022-06-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messages_blog_messages_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.CharField(max_length=240),
        ),
    ]
