# Generated by Django 4.0.4 on 2022-06-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messages_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='autor',
            new_name='author',
        ),
    ]
