# Generated by Django 4.0.4 on 2022-05-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request',
            new_name='text',
        ),
    ]
