# Generated by Django 4.0.4 on 2022-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_request_request_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
