# Generated by Django 4.0.4 on 2022-06-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_avatar_delete_user_blog_image1_blog_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
