# Generated by Django 4.0.4 on 2022-06-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
    ]
