# Generated by Django 4.0.4 on 2022-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_autor_remove_request_votes_blog_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='vote_list',
        ),
        migrations.AddField(
            model_name='request',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
